server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.79.176
aliyun:
  sms:
    accessKeyId: 
    accessKeySecret:
    template_code: 
    sign_name: 小伙伴短信验证码服务
